# Generated by tools/update_python_targets.py -- do not edit by hand.
#
# The interpreter set is .python-version; flake.nix asserts the two agree.
# Headers come from python-build-standalone because a cross build needs the
# target's pyconfig.h, and nixpkgs has no Windows or Darwin CPython.
{
  release = "20260718";

  platforms = {
    manylinux-x86_64 = {
      pbsTriple = "x86_64-unknown-linux-gnu";
      zigTarget = "x86_64-linux-gnu.2.17";
      platformTag = "manylinux_2_17_x86_64";
      moduleName = "record.cpython-{nodot}-x86_64-linux-gnu.so";
      extraFlags = [ ];
      linkPythonLibrary = false;
    };
    manylinux-aarch64 = {
      pbsTriple = "aarch64-unknown-linux-gnu";
      zigTarget = "aarch64-linux-gnu.2.17";
      platformTag = "manylinux_2_17_aarch64";
      moduleName = "record.cpython-{nodot}-aarch64-linux-gnu.so";
      extraFlags = [ ];
      linkPythonLibrary = false;
    };
    macos-x86_64 = {
      pbsTriple = "x86_64-apple-darwin";
      zigTarget = "x86_64-macos.10.13";
      platformTag = "macosx_10_13_x86_64";
      moduleName = "record.cpython-{nodot}-darwin.so";
      extraFlags = [
        "-undefined"
        "dynamic_lookup"
      ];
      linkPythonLibrary = false;
    };
    macos-aarch64 = {
      pbsTriple = "aarch64-apple-darwin";
      zigTarget = "aarch64-macos.11.0";
      platformTag = "macosx_11_0_arm64";
      moduleName = "record.cpython-{nodot}-darwin.so";
      extraFlags = [
        "-undefined"
        "dynamic_lookup"
      ];
      linkPythonLibrary = false;
    };
    windows-x86_64 = {
      pbsTriple = "x86_64-pc-windows-msvc";
      zigTarget = "x86_64-windows-gnu";
      platformTag = "win_amd64";
      moduleName = "record.pyd";
      extraFlags = [ ];
      linkPythonLibrary = true;
    };
    windows-aarch64 = {
      pbsTriple = "aarch64-pc-windows-msvc";
      zigTarget = "aarch64-windows-gnu";
      platformTag = "win_arm64";
      moduleName = "record.pyd";
      extraFlags = [ ];
      linkPythonLibrary = true;
    };
  };

  pythons = {
    "3.14" = {
      version = "3.14.6";
      tag = "cp314";
      hashes = {
        manylinux-x86_64 = "sha256-hr8Qf2X8MLVvKyY7Jnl/y7FmH1MVkQzb8n9zPrhzi3Q=";
        manylinux-aarch64 = "sha256-wqLKoDqpvrd6W7taAJyP53uWpWkl2i26GAlSN+MPrwQ=";
        macos-x86_64 = "sha256-LQMVS8g8bS0Ei7oju4CLAg41ICj1vVQadA5URn/JzHU=";
        macos-aarch64 = "sha256-Xo4HRssBCNE49RDPuyjEsDG57WO7vj5Do0x31GY8T6E=";
        windows-x86_64 = "sha256-DFyfIxcE+0kUm8jyudnb5D7q9sVPNi7w/CBmzmS00Q8=";
        windows-aarch64 = "sha256-iay5GE3PyzSGKQVJTkpBsn34+DZJU9V5bMD5FBFg1/k=";
      };
    };
    "3.13" = {
      version = "3.13.14";
      tag = "cp313";
      hashes = {
        manylinux-x86_64 = "sha256-VxpxDGJSCybbrb0W6IUOJFZcAd6pREAiO8FsqiFhQCE=";
        manylinux-aarch64 = "sha256-jVrGhFik35vDw0nWB9omdNg5CtJhYkgrFyFVY+RayoM=";
        macos-x86_64 = "sha256-k+w4Y+MmXthzgqkhbS6XO0erfvMwtJbAJJv8K/wWTO4=";
        macos-aarch64 = "sha256-BkaYNeGw9zvNtsSYodYM5XnMQ6mAdUSQpvHjAGL0OFA=";
        windows-x86_64 = "sha256-keoM2IMpVFj6dm6uNiQd8+zCH3ApgUGJcH1UtFDlXGk=";
        windows-aarch64 = "sha256-djcg/ymwF+KCEBp31609IyRpHu3EBSjZFsJIkFkkvio=";
      };
    };
    "3.12" = {
      version = "3.12.13";
      tag = "cp312";
      hashes = {
        manylinux-x86_64 = "sha256-WFSqbsccrQAzTVBlYzwhCy5/60CVZ2elmpF5HK3PC3k=";
        manylinux-aarch64 = "sha256-8iZXa5FJH/pXOaqFcmUh6QMfTYf4BifWTtNIrHfLMek=";
        macos-x86_64 = "sha256-jmt+ZTO990YocAjt+REC577gpsodJPFsRRQjfK/XBsU=";
        macos-aarch64 = "sha256-mh6eBhdcEO/YN4uQSwf6Ib15GrM0XXzf/rSnbJ/1WQM=";
        windows-x86_64 = "sha256-DUIqFDnsMI4D9H31Ubww9ZlHJ8RW5BSwJtICvNqbfBw=";
        windows-aarch64 = "sha256-WWgI0lkqKCxFkhoyTVUD7w1PSI0QTBwfEqHV596p1GM=";
      };
    };
    "3.11" = {
      version = "3.11.15";
      tag = "cp311";
      hashes = {
        manylinux-x86_64 = "sha256-I8yubx/3PoqoN4Q2+GnaADuOt9bJXyvHBvSUEVuhRH0=";
        manylinux-aarch64 = "sha256-1C3wRYYKcMyUsnUumIdIdhkBmPJPPhb4Pz7FrS1pbTE=";
        macos-x86_64 = "sha256-jKOQbtI/Soq0/48C1hsV7PYub6izEs1Z0Wkt806DSmU=";
        macos-aarch64 = "sha256-sh28Pz4Bky/MPw9MUeWn72GIjLRU0j7uboIHxvUtCwQ=";
        windows-x86_64 = "sha256-pIwtvoMjGfYaqFV8mQDK7HD3/tDL7jkaTJ/5+YtQIi0=";
        windows-aarch64 = "sha256-16RJrZlCCrqW8e5QfMmppkc8/InEEIM3F9R79dVE4fs=";
      };
    };
    "3.10" = {
      version = "3.10.20";
      tag = "cp310";
      hashes = {
        manylinux-x86_64 = "sha256-PXHHGq2BjasXdtypT3ZmfYgSbgZiPZFqITcRF9F9Iec=";
        manylinux-aarch64 = "sha256-dZDK1tRk2c/H8w7BWmq5GRE/oNJlQGiC+GBaedOkO/o=";
        macos-x86_64 = "sha256-GFt6Jl+npz0GlQ+TulpxUn6d4zyTV6NzVw6XBHq9le4=";
        macos-aarch64 = "sha256-WY2YktUCTbp8+6a7Nf5CXrEvhfJlv4HEr9/PBEIewZA=";
        windows-x86_64 = "sha256-z36uRoV9Pk7OnxRxHkd1ZgafvUz3h0ZYEyKE5RXSQvg=";
      };
    };
    "3.15" = {
      version = "3.15.0b4";
      tag = "cp315";
      hashes = {
        manylinux-x86_64 = "sha256-YlTntPT6WUEQ7dcY2GclEQA0QEjPW5gunGZAWvDfoTQ=";
        manylinux-aarch64 = "sha256-vf7eJ2Ll5mfzfuEYRbksEc6Mg5QVibnJgdL2vdeE7Rg=";
        macos-x86_64 = "sha256-Zo5SrtAZeN5Qrvh+F6INzAUw851S3O/jBnemv3rMxbQ=";
        macos-aarch64 = "sha256-F1vJxeEfbN/FecQSZB7TKmzzNtkavQAw1URWt7SMcVY=";
        windows-x86_64 = "sha256-sH0ql4izkvPQHkozEUuDPnEISeWWbdKaKNjY+r7rDvo=";
        windows-aarch64 = "sha256-hUMKBBrYppLB8llRfDb3q6t2g0QOUDfgCh5tKg8j1rk=";
      };
    };
  };
}
